### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by linkmoises** [mbehrle/docker-gnuhealth-demo#2]
Hello I'm using Arch Linux. Mi tryton client version is 3.4.8. I'm using the tutorial connect data:

> Host: 127.0.0.1:8000
> Database: health28
> User name: admin
> Password: gnusolidario

But I'm unable to connect to the server.

```
[root@laptop gnuhealth]# docker-compose up
Starting gnuhealth_db_1
Starting gnuhealth_tryton_1
Attaching to gnuhealth_db_1, gnuhealth_tryton_1
db_1     | LOG:  database system was shut down at 2016-03-11 16:28:15 UTC
tryton_1 | [Fri Mar 11 16:28:19 2016] INFO:trytond.server:using /etc/tryton/trytond.conf as configuration file
tryton_1 | [Fri Mar 11 16:28:19 2016] INFO:trytond.server:initialising distributed objects services
db_1     | LOG:  MultiXact member wraparound protections are now enabled
db_1     | LOG:  database system is ready to accept connections
db_1     | LOG:  autovacuum launcher started
tryton_1 | [Fri Mar 11 16:28:19 2016] INFO:trytond.server:starting JSON-RPC protocol on :::8000
tryton_1 | [Fri Mar 11 16:28:27 2016] INFO:database:connect to "health28"
tryton_1 | [Fri Mar 11 16:28:38 2016] INFO:database:connect to "health28"
tryton_1 | [Fri Mar 11 16:28:48 2016] INFO:database:connect to "health28"
```

The first time I was using the wrong tryton client version (3.8). But now I'm using the correct version according to the server (3.4.8) and I'm getting a logging error.

> Connection error!
> Bad username or password!

This is the docker install log:

```
[root@laptop gnuhealth]# docker-compose up
Pulling db (mbsolutions/postgres-gnuhealth:2.8)...
2.8: Pulling from mbsolutions/postgres-gnuhealth
f8efbffe7b95: Pull complete
a3ed95caeb02: Pull complete
64bb2775d20d: Pull complete
112aae0540bb: Pull complete
96d2a7a4fcb3: Pull complete
8d43a1a2d52b: Pull complete
1eba7ded6f54: Pull complete
72377f1d0630: Pull complete
5b95ba5f224f: Pull complete
b91c5ed5aea8: Pull complete
1c9d3fc5a296: Pull complete
793d7d756766: Pull complete
9cd28ddb9d7e: Pull complete
c5047e1e2cb6: Pull complete
Digest: sha256:5651dd9c0984b201d22b6607ff1d782c04c4549c9ebb553d4004bf5ac518618d
Status: Downloaded newer image for mbsolutions/postgres-gnuhealth:2.8
Creating gnuhealth_db_1
Pulling tryton (mbsolutions/tryton-server-gnuhealth:3.4)...
3.4: Pulling from mbsolutions/tryton-server-gnuhealth
237d5fcd25cf: Pull complete
a3ed95caeb02: Pull complete
a0786d63385a: Pull complete
d895343f2b4c: Pull complete
a9d6577b36bd: Pull complete
28733ddfe9f8: Pull complete
f7be68864363: Pull complete
f2c00534caf3: Pull complete
b6a203dcd5b3: Pull complete
Digest: sha256:ff6c119c69ab31324799d84495bb25e0d48b84ff4f34e5f074b75f7f7512382a
Status: Downloaded newer image for mbsolutions/tryton-server-gnuhealth:3.4
Creating gnuhealth_tryton_1
Attaching to gnuhealth_db_1, gnuhealth_tryton_1
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     | 
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     | 
db_1     | Data page checksums are disabled.
db_1     | 
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting dynamic shared memory implementation ... posix
db_1     | creating configuration files ... ok
db_1     | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1     | initializing pg_authid ... ok
db_1     | initializing dependencies ... ok
db_1     | creating system views ... ok
db_1     | loading system objects' descriptions ... ok
db_1     | creating collations ... ok
db_1     | creating conversions ... ok
db_1     | creating dictionaries ... ok
db_1     | setting privileges on built-in objects ... ok
db_1     | creating information schema ... ok
db_1     | loading PL/pgSQL server-side language ... ok
db_1     | vacuuming database template1 ... ok
db_1     | copying template1 to template0 ... ok
db_1     | copying template1 to postgres ... ok
db_1     | syncing data to disk ... ok
db_1     | 
db_1     | Success. You can now start the database server using:
db_1     | 
db_1     |     postgres -D /var/lib/postgresql/data
db_1     | or
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     | 
db_1     | 
db_1     | WARNING: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | waiting for server to start....LOG:  database system was shut down at 2016-03-11 15:25:10 UTC
db_1     | LOG:  MultiXact member wraparound protections are now enabled
db_1     | LOG:  autovacuum launcher started
db_1     | LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
db_1     | ALTER ROLE
db_1     | 
db_1     | 
db_1     | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/gnuhealth.sh
db_1     | FATAL:  lock file "postmaster.pid" already exists
db_1     | HINT:  Is another postmaster (PID 60) running in data directory "/var/lib/postgresql/data"?
gnuhealth_db_1 exited with code 1
tryton_1 | [Fri Mar 11 15:38:07 2016] INFO:trytond.server:using /etc/tryton/trytond.conf as configuration file
tryton_1 | [Fri Mar 11 15:38:07 2016] INFO:trytond.server:initialising distributed objects services
tryton_1 | [Fri Mar 11 15:38:07 2016] INFO:trytond.server:starting JSON-RPC protocol on :::8000
tryton_1 | ::ffff:172.17.0.1 - - [11/Mar/2016 15:41:53] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03z\x89\xd4\xc9\x0f\x12\xdc\xab\x7f\xdc\xf6\xa1\xbc$\x84\x018\x8d\xddA\x99\xd3\x85Ign\x02\x9c\xf2\xac/\x88\x00\x00\x94\xc00\xc0,\xc02\xc0.\xc0/\xc0+\xc01\xc0-\x00\xa5\x00\xa3\x00\xa1\x00\x9f\x00\xa4\x00\xa2\x00\xa0\x00\x9e\xc0(\xc0$\xc0\x14\xc0')

^CGracefully stopping... (press Ctrl+C again to force)
Stopping gnuhealth_tryton_1 ... done
```

**Comment by mbehrle** [comment]
- Moisés Serrano: " [docker-gnuhealth-demo] Connection error (#2)" (Fri, 11 Mar
  2016 08:37:35 -0800):

Hi,

did you retry with
$ docker-compose up

It seems there was a problem with conflicting postgresql processes.

> Hello I'm using Arch Linux. Mi tryton client version is 3.4.8. I'm using the
> tutorial connect data:
> 
> > Host: 127.0.0.1:8000
> > Database: health28
> > User name: admin
> > Password: gnusolidario  
> 
> But I'm unable to connect to the server.
> 
> ``````
> [root@laptop gnuhealth]# docker-compose up
> Starting gnuhealth_db_1
> Starting gnuhealth_tryton_1
> Attaching to gnuhealth_db_1, gnuhealth_tryton_1
> db_1     | LOG:  database system was shut down at 2016-03-11 16:28:15 UTC
> tryton_1 | [Fri Mar 11 16:28:19 2016]
> INFO:trytond.server:using /etc/tryton/trytond.conf as configuration file
> tryton_1 | [Fri Mar 11 16:28:19 2016] INFO:trytond.server:initialising
> distributed objects services db_1     | LOG:  MultiXact member wraparound
> protections are now enabled db_1     | LOG:  database system is ready to
> accept connections db_1     | LOG:  autovacuum launcher started tryton_1 |
> [Fri Mar 11 16:28:19 2016] INFO:trytond.server:starting JSON-RPC protocol
> on :::8000 tryton_1 | [Fri Mar 11 16:28:27 2016] INFO:database:connect to
> "health28" tryton_1 | [Fri Mar 11 16:28:38 2016] INFO:database:connect to
> "health28" tryton_1 | [Fri Mar 11 16:28:48 2016] INFO:database:connect to
> "health28" ``` The first time I was using the wrong tryton client version
> (3.8). But now I'm using the correct version according to the server (3.4.8)
> and I'm getting a logging error.
> 
> > Connection error!
> > Bad username or password!  
> 
> This is the docker install log:
> ``````
> 
> [root@laptop gnuhealth]# docker-compose up
> Pulling db (mbsolutions/postgres-gnuhealth:2.8)...
> 2.8: Pulling from mbsolutions/postgres-gnuhealth
> f8efbffe7b95: Pull complete
> a3ed95caeb02: Pull complete
> 64bb2775d20d: Pull complete
> 112aae0540bb: Pull complete
> 96d2a7a4fcb3: Pull complete
> 8d43a1a2d52b: Pull complete
> 1eba7ded6f54: Pull complete
> 72377f1d0630: Pull complete
> 5b95ba5f224f: Pull complete
> b91c5ed5aea8: Pull complete
> 1c9d3fc5a296: Pull complete
> 793d7d756766: Pull complete
> 9cd28ddb9d7e: Pull complete
> c5047e1e2cb6: Pull complete
> Digest:
> sha256:5651dd9c0984b201d22b6607ff1d782c04c4549c9ebb553d4004bf5ac518618d
> Status: Downloaded newer image for mbsolutions/postgres-gnuhealth:2.8
> Creating gnuhealth_db_1 Pulling tryton
> (mbsolutions/tryton-server-gnuhealth:3.4)... 3.4: Pulling from
> mbsolutions/tryton-server-gnuhealth 237d5fcd25cf: Pull complete
> a3ed95caeb02: Pull complete
> a0786d63385a: Pull complete
> d895343f2b4c: Pull complete
> a9d6577b36bd: Pull complete
> 28733ddfe9f8: Pull complete
> f7be68864363: Pull complete
> f2c00534caf3: Pull complete
> b6a203dcd5b3: Pull complete
> Digest:
> sha256:ff6c119c69ab31324799d84495bb25e0d48b84ff4f34e5f074b75f7f7512382a
> Status: Downloaded newer image for mbsolutions/tryton-server-gnuhealth:3.4
> Creating gnuhealth_tryton_1 Attaching to gnuhealth_db_1, gnuhealth_tryton_1
> db_1     | The files belonging to this database system will be owned by user
> "postgres". db_1     | This user must also own the server process.
> db_1     | 
> db_1     | The database cluster will be initialized with locale "en_US.utf8".
> db_1     | The default database encoding has accordingly been set to "UTF8".
> db_1     | The default text search configuration will be set to "english".
> db_1     | 
> db_1     | Data page checksums are disabled.
> db_1     | 
> db_1     | fixing permissions on existing
> directory /var/lib/postgresql/data ... ok db_1     | creating
> subdirectories ... ok db_1     | selecting default max_connections ... 100
> db_1     | selecting default shared_buffers ... 128MB
> db_1     | selecting dynamic shared memory implementation ... posix
> db_1     | creating configuration files ... ok
> db_1     | creating template1 database in /var/lib/postgresql/data/base/1 ...
> ok db_1     | initializing pg_authid ... ok
> db_1     | initializing dependencies ... ok
> db_1     | creating system views ... ok
> db_1     | loading system objects' descriptions ... ok
> db_1     | creating collations ... ok
> db_1     | creating conversions ... ok
> db_1     | creating dictionaries ... ok
> db_1     | setting privileges on built-in objects ... ok
> db_1     | creating information schema ... ok
> db_1     | loading PL/pgSQL server-side language ... ok
> db_1     | vacuuming database template1 ... ok
> db_1     | copying template1 to template0 ... ok
> db_1     | copying template1 to postgres ... ok
> db_1     | syncing data to disk ... ok
> db_1     | 
> db_1     | Success. You can now start the database server using:
> db_1     | 
> db_1     |     postgres -D /var/lib/postgresql/data
> db_1     | or
> db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
> db_1     | 
> db_1     | 
> db_1     | WARNING: enabling "trust" authentication for local connections
> db_1     | You can change this by editing pg_hba.conf or using the option -A,
> or db_1     | --auth-local and --auth-host, the next time you run initdb.
> db_1     | waiting for server to start....LOG:  database system was shut down
> at 2016-03-11 15:25:10 UTC db_1     | LOG:  MultiXact member wraparound
> protections are now enabled db_1     | LOG:  autovacuum launcher started
> db_1     | LOG:  database system is ready to accept connections
> db_1     |  done
> db_1     | server started
> db_1     | ALTER ROLE
> db_1     | 
> db_1     | 
> db_1     | /docker-entrypoint.sh:
> running /docker-entrypoint-initdb.d/gnuhealth.sh db_1     | FATAL:  lock file
> "postmaster.pid" already exists db_1     | HINT:  Is another postmaster (PID
> 60) running in data directory "/var/lib/postgresql/data"? gnuhealth_db_1
> exited with code 1 tryton_1 | [Fri Mar 11 15:38:07 2016]
> INFO:trytond.server:using /etc/tryton/trytond.conf as configuration file
> tryton_1 | [Fri Mar 11 15:38:07 2016] INFO:trytond.server:initialising
> distributed objects services tryton_1 | [Fri Mar 11 15:38:07 2016]
> INFO:trytond.server:starting JSON-RPC protocol on :::8000 tryton_1
> | ::ffff:172.17.0.1 - - [11/Mar/2016 15:41:53] code 400, message Bad request
> | syntax
> | ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03z\x89\xd4\xc9\x0f\x12\xdc\xab\x7f\xdc\xf6\xa1\xbc$\x84\x018\x8d\xddA\x99\xd3\x85Ign\x02\x9c\xf2\xac/\x88\x00\x00\x94\xc00\xc0,\xc02\xc0.\xc0/\xc0+\xc01\xc0-\x00\xa5\x00\xa3\x00\xa1\x00\x9f\x00\xa4\x00\xa2\x00\xa0\x00\x9e\xc0(\xc0$\xc0\x14\xc0')
> 
> ^CGracefully stopping... (press Ctrl+C again to force)
> Stopping gnuhealth_tryton_1 ... done
> 
> ```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mbehrle/docker-gnuhealth-demo/issues/2
> 
> 
> ```

## 

```
Mathias Behrle
PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6
```

**Comment by linkmoises** [comment]
Hi. Same problem when retry.

I've seen similar problems in other projects [https://github.com/stefansiegl/docker-introscope/issues/1](url).

What do you think about this solution: [https://github.com/docker-library/postgres/issues/78#issuecomment-125580293](url)

This is the docker output when retry: [docker-output.txt](https://github.com/mbehrle/docker-gnuhealth-demo/files/170503/docker-output.txt)

**Comment by mbehrle** [comment]
Thanks for reporting. Should be fixed by adapting to the changed initdb logic of the postgres container.
