### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by herrsergio** [mbehrle/docker-gnuhealth-demo#3]
It would be great if you can use the latest version of GNU Health. Have you planned to update it ?

**Comment by mbehrle** [comment]
I have rather decided not to continue this docker demo. AFAIR there was an incentive to create a docker file by the project itself.

**Comment by herrsergio** [comment]
OK, thank you for your quick answer. Unfortunately the project hasn't created a Docker file yet. In the instructions it still mentions your [project](https://en.wikibooks.org/wiki/GNU_Health/Different_ways_to_test_GNU_Health#Option_4:_Run_GNU_Health_from_Docker_(Lightweight_Containers))
